
# File format info: https://moz-l10n-config.readthedocs.io/en/latest/fileformat.html
basepath = "."

locales = [
    "es-419",
    "nl"
]

[[paths]]
    reference = "po/en/messages.pot"
    l10n = "po/{locale}/messages.po"